Task02_Kuzivanov
SpirinEgor/python_basic_programming pull request #1
Opened 2020-03-14 15:48 UTC by SergeyKuz1001

2020-03-15 15:28 UTC, SpirinEgor requested changes

2020-03-15 15:28 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +    return dict
Можно просто `dict(list)`

2020-03-15 15:28 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +        str(profile_full)
Можно использовать f-строку
```
f'''
text
{profile_short}
'''
```

2020-03-15 15:28 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +    );""")
Можно использовать `UPDATE`

2020-03-15 15:28 UTC, SpirinEgor commented on assignment_2/client/data_worker.js
> +    $.get('http://127.0.0.1:5000/add_account?screen_name=' + screen_name,
Параметр `screen_name` лучше передавать отдельно, а не вставлять прям в url

2020-03-15 15:28 UTC, SpirinEgor commented on assignment_2/client/data_worker.js
> -const form = document.getElementById('form');
Конечно, в js можно и не ставить `;`
Но, [style guide](https://google.github.io/styleguide/jsguide.html) всё же рекомендует это делать

2020-03-15 15:28 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +        '''</div>''' +
А для чего нужно оборачивать поверх отдельным html?

2020-03-15 20:18 UTC, SergeyKuz1001 commented on assignment_2/server/app_db.py
> +        '''</div>''' +
Для того, чтобы объединить profile_short и profile_full в profile и работать с ним как со всей информацией о профиле. Иными словами, мне кажется, что лучше сначала объединить profile_short и profile_full и потом преобразовать в json, чем наоборот.

2020-05-25 12:58 UTC, SpirinEgor requested changes
Проверь на pep8 и используй POST запрос

2020-05-25 12:58 UTC, SpirinEgor commented on assignment_2/client/data_worker.js
> +    $.get('http://127.0.0.1:5000/add_account?screen_name=' + screen_name,
Всё ещё Get запрос, для передачи данных на сервер лучше использовать Post запрос

2020-05-25 12:58 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +    req = requests.get(url, headers = header)
pep8 местами не соблюдается, например, тут

2020-05-26 18:17 UTC, SpirinEgor approved these changes

2020-05-26 18:18 UTC, closed without merging