Task02_Lunev
SpirinEgor/python_basic_programming pull request #14
Opened 2020-03-16 19:18 UTC by artemlunev2000

2020-03-24 16:17 UTC, SpirinEgor requested changes
pep8 немного ругается, проверь им

2020-03-24 16:17 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +                   ("MSU", item.text, item['href']))
Я бы разнёс это по отдельным функциям.
Так же, добавление данных не относится к инициализации, поэтому либо вызывать после `init_db()`, либо через кнопочки с клиента

2020-03-24 16:17 UTC, SpirinEgor commented on assignment_2/client/index.html
> +            <th scope="col">Link</th>
Ссылки неплохо было бы кликабельными сделать

2020-04-10 19:59 UTC, artemlunev2000 commented
@SpirinEgor, поправил

2020-04-14 09:14 UTC, SpirinEgor approved these changes

2020-04-14 09:15 UTC, closed without merging