Task02_Abzalov
SpirinEgor/python_basic_programming pull request #16
Opened 2020-03-16 19:49 UTC by viabzalov

2020-03-24 16:35 UTC, SpirinEgor requested changes
1. Залетели файлы из `assignment_1`
2. Файлы самой бд на гит класть не надо
3. Недавно говорил, почему не стоит использовать темплейты, так что хочется увидеть клиент-серверное решение
4. pep8

Можешь рассказать про создание использование бд? Хочется, чтобы при запуске `main.py` запускалась бд без лишних телодвижений. `app_db_creator.py` вообще не используется, судя по всему. Не очень понятно.

2020-03-24 16:35 UTC, SpirinEgor commented on assignment_2/main.py
> +        game.rank = str(find_rank.text if find_rank !=
`find_rank is not None`

2020-03-24 16:35 UTC, SpirinEgor commented on assignment_2/main.py
> +        game.rating = str(find_rating.text if find_rating !=
А зачем тут и в подобных местах к `str` приводить? `.text` разве не строку возвращает?

2020-03-24 16:35 UTC, SpirinEgor commented on assignment_2/main.py
> +            bgg_url + "{}".format(game.title)).content, "html.parser")
`f"{game.title}"`

2020-03-24 16:35 UTC, SpirinEgor commented on assignment_2/main.py
> +init_db()
Не лучшее место для вызова функции, так как каждый раз исполняется при вызове файла в интерпретаторе, даже если этот файл будет где-то импортирован. Лучше всего засунуть в `if __name__ ==  '__main__'`

2020-03-24 16:35 UTC, SpirinEgor commented on assignment_2/app_db_setup.py
> +    import models
`import` обычно всё-так в начале файла пишут, что не заставлять импортировать модуль при каждом вызове функции.

2020-03-24 16:35 UTC, SpirinEgor commented on assignment_2/app_db_creator.py
> +    stock = Column(String)
Почти такой же класс есть в `models.py`

2020-04-20 11:17 UTC, SpirinEgor requested changes

2020-04-20 11:17 UTC, SpirinEgor commented on assignment_2/app_db_setup.py
> +    import app_db_creator
Эти импорты не используются, их надо удалить

2020-04-20 11:17 UTC, SpirinEgor commented on assignment_2/app_db_creator.py
> +Base = declarative_base()
Если эти строчки надо выполнять при инициализации бд, то лучше вынести в отдельную функцию и вызывать её, чем импортировать целый файл для работы интерпретатора

2020-04-20 11:17 UTC, SpirinEgor commented on assignment_2/main.py
> +    return render_template('index.html', form=search_form)
В этом задание ожидается увидеть клиент-серверное взаимодействие. Сервер отдаёт json, а клиент (js) принимает его и отображает на разметке

2020-04-20 18:09 UTC, viabzalov commented on assignment_2/main.py
> +    return render_template('index.html', form=search_form)
Переписал на клиент-серверное взаимодействие

2020-04-21 12:12 UTC, SpirinEgor approved these changes

2020-04-21 12:12 UTC, closed without merging