Task02_Privalikhin
SpirinEgor/python_basic_programming pull request #2
Opened 2020-03-15 18:58 UTC by AlekseiPrivalihin

2020-03-19 10:49 UTC, SpirinEgor requested changes
pep8 сильно ругается, проверь им свой код

2020-03-19 10:49 UTC, SpirinEgor commented on assignment_2/server/app_base.py
> +    return 'Zalupa'
Хорошего программиста видно издалека

2020-03-19 10:49 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +'''@app.route('/new_user', methods=['POST'])
Это не способ комментирования, так ты создаёшь строчку. Если код не нужен, то его можно удалить, не зачем его хранить.

2020-03-19 10:49 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +    return (tag.a['aria-label'], "<a href=\"" + tag.a['href'] + "\">Find out more!</a>")
Для составления строк можно использовать `f` строки, с ними получается аккуратнее.
```
f'<a href="{url}"...'
```

2020-03-19 10:49 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +                PewNews.append((link.text.strip(), "<a href=\"" + link['href'] + "\">Find out more!</a>"))
Парсинг сайтов можно вынести в отдельную функцию, а то `init_db` получается большой.

2020-03-19 10:49 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +            cursor.execute("""INSERT INTO PewNews (name,link) VALUES(?,?);""", (news[0], news[1]))
Это можно сделать за один `insert`

2020-03-19 10:49 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +        PewNews = []
в питоне переменные принято называть `snake_case`

2020-05-31 16:03 UTC, AlekseiPrivalihin commented
Внес требуемые правки и проверил код pep8

2020-06-02 12:47 UTC, SpirinEgor approved these changes

2020-06-02 12:48 UTC, closed without merging