Task02_Vlaev
SpirinEgor/python_basic_programming pull request #3
Opened 2020-03-15 20:45 UTC by nikitavlaev

2020-03-19 11:00 UTC, SpirinEgor requested changes
У тебя получается ручное заполнение базы данных: надо запустить ноутбук и прощелкать ячейки. Хочется это автоматизировать: либо вызывать соответствующие функции, либо сделать кнопку на сайте, чтобы по нажатию собиралась информация из соответствующего источника.

2020-03-24 17:43 UTC, SpirinEgor requested changes
Проверь с pep8

2020-03-24 17:43 UTC, SpirinEgor commented on assignment_2/client/data_worker.js
> +            document.getElementById('load-src1').style.background = "#007bff";
Не очень понял, что ты тут с кнопкой для первого источника делаешь?

2020-03-24 17:43 UTC, SpirinEgor commented on assignment_2/client/index.html
> +            <th scope="col" style="width: 45%;">Link</th>
Ссылки лучше всего кликабельными делать, а не просто как текст вставлять

2020-03-24 17:43 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +def src_1():
такие названия функций вообще ужасны. Везде используется этот `src_1`, но непонятно что он из себя представляет.

2020-03-26 19:05 UTC, nikitavlaev commented on assignment_2/client/data_worker.js
> +            document.getElementById('load-src1').style.background = "#007bff";
Когда табличка подгружается, кнопочка становится красной.
Был косяк, забыл это добавить для других кнопок.
Сейчас все пофикшено.

2020-03-30 07:23 UTC, SpirinEgor approved these changes

2020-03-30 07:23 UTC, closed without merging