Task03_Sukhanova
SpirinEgor/python_basic_programming pull request #33
Opened 2020-04-05 22:36 UTC by AnzhelaSukhanova

Image Сolorization

2020-04-06 08:56 UTC, SpirinEgor requested changes
Всё работает замечательно. Но надо немного подправить код (pep8) и в pr попало очень много ненужных файлов, должно быть 6 файлов, а у тебя 32.

2020-04-06 08:56 UTC, SpirinEgor commented on Task03/app.py
> +    weightsFile = "./models/colorization_release_v2.caffemodel"
snake_case

2020-04-06 10:07 UTC, AnzhelaSukhanova commented on Task03/app.py
> +    weightsFile = "./models/colorization_release_v2.caffemodel"
Я подправила код, но не знаю, что делать с лишними файлами :( Я их специально удаляла, чтобы в pr не попало ничего ненужного, но, видимо, что-то не так сделала

2020-04-09 09:33 UTC, SpirinEgor reviewed
Легче всего переоткрыть pull request без лишних файлов, надо синхронизировать эту ветку с мастером и оставить разницу только в файлах из этого задания. В крайнем случае,  можешь сделать новую ветку от мастера, и в неё перенести файлы задания, но тогда потеряется история коммитов. Если будут вопросы, лучше пиши в телеграмме.

2020-04-09 14:37 UTC, SpirinEgor approved these changes

2020-04-14 08:49 UTC, closed without merging