Task03_Pogozhelskaya
SpirinEgor/python_basic_programming pull request #36
Opened 2020-04-15 03:01 UTC by Pogozhelskaya

Pose estimation

2020-04-20 11:44 UTC, SpirinEgor requested changes

2020-04-20 11:44 UTC, SpirinEgor commented on assignment_3/pose_estimation/app.py
> +    frame = cv2.imread(filename)
`filename` тут без учёта папки `uploads`, поэтому дальше всё ломается.

2020-04-20 11:44 UTC, SpirinEgor commented on assignment_3/pose_estimation/app.py
> +    W = output.shape[3]
Местами переменные не по styleguide. Поправь тут и дальше

2020-04-20 12:13 UTC, Pogozhelskaya commented on assignment_3/pose_estimation/app.py
> +    frame = cv2.imread(filename)
Ой, у меня файл всегда был в той же директории, не заметила. Исправила

2020-04-21 12:17 UTC, SpirinEgor approved these changes

2020-04-21 12:18 UTC, closed without merging