Assignment 2
SpirinEgor/python_basic_programming pull request #9
Opened 2020-03-16 14:42 UTC by AfoninaOlga

2020-03-16 14:50 UTC, AlanGamaonov commented
Оля, переименуй пр, перфекционист плачет! 

![а](https://user-images.githubusercontent.com/42998371/76770180-8fa2c100-67ae-11ea-8800-635f5d966549.jpg)

2020-03-16 15:19 UTC, AlanGamaonov commented
Спасибо)

2020-03-24 18:04 UTC, SpirinEgor requested changes
`pep8`

2020-03-24 18:04 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +                Products.append(('Xiaomi', prod.text))
Инициализация бд -- проверка на существование необходимым таблиц и их создание по необходимости. Это не имеет отношения к наполнению контентом. Поэтому лучше вынести парсинг сайтов в отдельные функции (каждый сайт в свою) и вызывать эти функции после `init_db()`. Так же можно в клиенте сделать кнопки для каждого источника и добавлять данные в таблицу только по нажатию на кнопку.

2020-04-11 14:42 UTC, AfoninaOlga commented on assignment_2/server/app_db.py
> +                Products.append(('Xiaomi', prod.text))
Вынесла заполнение базы из инициализации.  Pep8 не ругается

2020-04-14 09:11 UTC, SpirinEgor approved these changes

2020-04-14 09:11 UTC, closed without merging